FROM gitpod/workspace-full@sha256:4cd82d34678edda8e68cfce0891d4580629f98806f3df94dd8d83572e5d88457

ARG DEBIAN_FRONTEND=noninteractive

CMD ["/bin/bash", "-l"]

COPY scripts/install/apt_packages.sh /setup/install/apt_packages.sh
RUN bash /setup/install/apt_packages.sh

COPY scripts/install/rust_tooling.sh /setup/install/rust_tooling.sh
RUN bash /setup/install/rust_tooling.sh

COPY scripts/install/cargo_tooling.sh /setup/install/cargo_tooling.sh
RUN bash /setup/install/cargo_tooling.sh

COPY scripts/install/container_tooling.sh /setup/install/container_tooling.sh
RUN sudo bash /setup/install/container_tooling.sh

COPY scripts/install/act.sh /setup/install/act.sh
RUN bash /setup/install/act.sh
