FROM gitpod/workspace-full@sha256:4848c05c108e2f62ab14cae074a3528d1e6092d2ff003a6aa95992c756ec714a

ARG DEBIAN_FRONTEND=noninteractive

CMD ["/bin/bash", "-l"]

COPY scripts/install/apt_packages.sh /setup/install/apt_packages.sh
RUN bash /setup/install/apt_packages.sh

COPY scripts/install/rust_tooling.sh /setup/install/rust_tooling.sh
RUN bash /setup/install/rust_tooling.sh

COPY scripts/install/cargo_tooling.sh /setup/install/cargo_tooling.sh
RUN bash /setup/install/cargo_tooling.sh

COPY scripts/install/container_tooling.sh /setup/install/container_tooling.sh
RUN sudo bash /setup/install/container_tooling.sh

COPY scripts/install/act.sh /setup/install/act.sh
RUN bash /setup/install/act.sh
