FROM gitpod/workspace-full@sha256:230285e0b949e6d728d384b2029a4111db7b9c87c182f22f32a0be9e36b225df

ARG DEBIAN_FRONTEND=noninteractive

CMD ["/bin/bash", "-l"]

COPY scripts/install/apt_packages.sh /setup/install/apt_packages.sh
RUN bash /setup/install/apt_packages.sh

COPY scripts/install/rust_tooling.sh /setup/install/rust_tooling.sh
RUN bash /setup/install/rust_tooling.sh

COPY scripts/install/cargo_tooling.sh /setup/install/cargo_tooling.sh
RUN bash /setup/install/cargo_tooling.sh

COPY scripts/install/container_tooling.sh /setup/install/container_tooling.sh
RUN sudo bash /setup/install/container_tooling.sh

COPY scripts/install/act.sh /setup/install/act.sh
RUN bash /setup/install/act.sh
