FROM mcr.microsoft.com/vscode/devcontainers/rust@sha256:a5e4aa0e2e1ba0d60e383d13d582f08fe98e29da09408656238aa2cc052e7545

ARG DEBIAN_FRONTEND=noninteractive

CMD ["/bin/bash", "-l"]

COPY scripts/install/apt_packages.sh /setup/install/apt_packages.sh
RUN bash /setup/install/apt_packages.sh

COPY scripts/install/rust_tooling.sh /setup/install/rust_tooling.sh
RUN bash /setup/install/rust_tooling.sh

COPY scripts/install/cargo_tooling.sh /setup/install/cargo_tooling.sh
RUN bash /setup/install/cargo_tooling.sh

COPY scripts/install/container_tooling.sh /setup/install/container_tooling.sh
RUN sudo bash /setup/install/container_tooling.sh

COPY scripts/install/act.sh /setup/install/act.sh
RUN bash /setup/install/act.sh