[package]
name = "install-from-manifest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_toml = "0.11.7"
indicatif = "0.17.0"
yansi = "0.5.1"
