[package]
name = "install-from-manifest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_toml = "0.20.0"
indicatif = "0.17.8"
yansi = "1.0.0"
