[package]
name = "dependency-tracking"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cargo-all-features = "1.7.0"
cargo-audit = "0.17.0" 
cargo-benchcmp = "0.4.3"
cargo-binstall = "0.9.2"
cargo-expand = "1.0.27" 
cargo-geiger = "0.11.3" 
cargo-license = "0.4.2"
cargo-linked = "0.1.0"
cargo-nextest = "0.9.24"
cargo-outdated = "0.11.1"  
cargo-sort = "1.0.7"
cargo-spellcheck = "0.11.3"
cargo-tarpaulin = "0.20.1"
cargo-tomlfmt = "0.1.3"
cargo-udeps = "0.1.30"
cargo-watch = "8.1.2" 
cargo-whatfeatures = "0.9.7"
diesel_cli = "1.4.1"  
flamegraph = "0.6.1"
