[package]
name = "dependency-tracking"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cargo-all-features = "1.7.0"
cargo-audit = "0.17.0" 
cargo-benchcmp = "0.4.3"
cargo-binstall = "0.21.3"
cargo-expand = "1.0.40" 
cargo-geiger = "0.11.5" 
cargo-license = "0.5.1"
cargo-linked = "0.1.0"
cargo-nextest = "0.9.50"
cargo-outdated = "0.11.1"  
cargo-sort = "1.0.7"
cargo-spellcheck = "0.12.2"
cargo-tarpaulin = "0.21.0"
cargo-tomlfmt = "0.1.3"
cargo-udeps = "0.1.34"
cargo-watch = "8.1.2" 
cargo-whatfeatures = "0.9.9"
diesel_cli = "2.0.0"  
flamegraph = "0.6.2"
