[dependencies]
cargo-watch = "8.1.1" 
cargo-outdated = "0.10.2"  
cargo-audit = "0.16.0" 
diesel_cli = "1.4.1"  
cargo-binstall = "0.5.0"
cargo-geiger = "0.11.2" 
cargo-all-features = "1.6.0"
cargo-whatfeatures = "0.9.7"
cargo-spellcheck = "0.9.6"
cargo-udeps = "0.1.25"
flamegraph = "0.5.1"