name: Build

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches:
      - "*"

jobs:
  container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        dockerfile: ["Containerfile.codespaces", "Containerfile.gitpod"]
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          image: ci