name: Build

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches:
      - "*"

jobs:
  container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        dockerfile: ["Containerfile.codespaces", "Containerfile.gitpod"]
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install qemu dependency
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/lib/jvm
          sudo rm -rf /opt/az
          sudo rm -rf /usr/lib/google-cloud-sdk
          sudo rm -rf /usr/lib/firefox
          sudo rm -rf /opt/google/chrome
          sudo rm -rf /opt/microsoft/powershell
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /usr/local/lib/android
          ls -a /usr/share
          ls -a /opt/
          ls -a /usr/lib/
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          image: ci
