name: Release

on:
  push:
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Process version of the tag
        id: version
        uses: ncipollo/semantic-version-action@v1

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          environment: docker-hub

      - name: Update deployment status (pending)
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          state: "pending"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Update deployment status (in_progress)
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          state: "in_progress"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Build Default
        env:
          VERSION: ${{ steps.version.outputs.tag }}
        run: docker buildx build --platform=linux/amd64 --push --tag chweicki/gitpod-rust-workspace:$VERSION --no-cache .

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://hub.docker.com/repository/docker/chweicki/gitpod-rust-workspace
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://hub.docker.com/repository/docker/chweicki/gitpod-rust-workspace
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}